### ISSUE TITLE
security.configured property in VMs

### ISSUE THREAD

**Issue by moltude** [dpla/marmotta-jetty#4]
When running Heidrun in a VM I am prompted for credentials when accessing the Marmotta SPARQL interface. It looks like the security.configured property in jetty/marmotta/system-config.properties is being set to TRUE in the Vagrant VM and FALSE locally. 

Even if a user edits this file and sets the property to false, when they restart jetty the property is reset to TRUE. 

![screen shot 2016-02-16 at 4 42 07 pm](https://cloud.githubusercontent.com/assets/1419766/13092165/84579984-d4cc-11e5-9bd4-cce34e9d74db.png)

**Comment by anarchivist** [comment]
I think this is by design in the Marmotta configuration - see the [Marmotta documentation](http://marmotta.apache.org/platform/security-module.html) and [this message](https://mail-archives.apache.org/mod_mbox/marmotta-users/201409.mbox/%3CCAGuvxyh1bwn3W4yY3bNE_V+kvN7sW7zvJgev0kdY9BeJrPSVYA@mail.gmail.com%3E).

> There are three pre-defined profiles, `simple`, `standard`, and `restricted`:
> - `simple` allows read access from everywhere and write access only from localhost or other local interfaces.
> - `standard` allows read access from everywhere and write access only for authenticated users of the “manager” role.
> - `restricted` allows access only for authenticated users.
> 
> By default, Marmotta will use the `simple` profile, allowing only access from localhost. 

Maybe we can have a chat w/ @markbreedlove about how to change the port forwarding config for Vagrant.

**Comment by moltude** [comment]
edit: 
may have written this too soon. more testing required.  so disregard for now, the only thing I have found this that changing the security setting is not persistent and is reset when jetty is restarted. 

curl -X POST -H "Content-Type: application/json" -d '["simple"]' http://<HOST>:<PORT>/marmotta/config/data/security.profile

**Comment by markbreedlove** [comment]
This might want to be closed. The upshot of what I told Scott the other day is I've never used Marmotta in a serious capacity in the `heidrun` VM. Whenever I really want to develop or test with Marmotta -- which is the only time I really pay attention to the configuration -- is in the `automation` VMs.

**Comment by no-reply** [comment]
Note that doing `rake jetty:start` locally allows access to the SPARQL interface.

This seems like a desirable feature for the `heidrun` VM. I haven't looked at the actual vagrant configuration, but it seems like it could be fixed there, per https://github.com/dpla/marmotta-jetty/issues/4#issuecomment-184895042.

In either case, I'm fine with closing this here, as it doesn't seem to be a Marmotta configuration issue, so much as a vagrant network config one.

**Comment by markbreedlove** [comment]
Closing and creating a ticket elsewhere to address the configuration in the VM.
